# Generated by Django 5.0.6 on 2024-08-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0002_remove_statusupdates_username_statusupdates_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='note',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
