# Generated by Django 5.0.6 on 2024-08-29 07:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0003_alter_registrations_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Blocked', 'Blocked')], max_length=8),
        ),
        migrations.AlterUniqueTogether(
            name='registrations',
            unique_together={('student', 'course')},
        ),
    ]
