# Generated by Django 5.0.6 on 2024-08-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0004_alter_registrations_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('BLOCKED', 'Blocked')], max_length=8),
        ),
    ]
