# Generated by Django 5.1 on 2024-09-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0007_chatmessages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessages',
            options={'verbose_name_plural': 'Chat Messages'},
        ),
        migrations.AlterField(
            model_name='appuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='elearning/uploads/profilePhotos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='file',
            field=models.FileField(blank=True, upload_to='elearning/uploads/courseMateral/%Y/%m/%d'),
        ),
    ]
