# Generated by Django 5.1 on 2024-09-01 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0008_alter_chatmessages_options_alter_appuser_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseduedates',
            name='file',
        ),
    ]
